language: python
python:
  - 2.7
install:
  - python bootstrap.py

# buildout step is separated into several steps as we are limited
# to 900 seconds per command: we install 'instance' and 'test' which
# are the biggest to steps followed by a general buildout steps that
# pulls in everything else
  - bin/buildout -q install instance
  - bin/buildout -q install test
  - bin/buildout -q

script:
  - ./pre-commit-check.sh
 
notifications:
  irc:
    - "irc.freenode.org#ngep"
  email:
    - it@eestec.net
