language: python
python:
  - 2.7
install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - python bootstrap.py
  - bin/buildout -t 2

script:
  - ./pre-commit-check.sh
 
notifications:
  irc:
    - "irc.freenode.org#ngep"
  email:
    - it@eestec.net
